export const SET_CUS_LEAD_INFO = 'SET_CUS_LEAD_INFO'

export const SET_LOGIN_INFO = 'SET_LOGIN_INFO'

export const SET_INTENTION_CAR_INFO = 'SET_INTENTION_CAR_INFO'

export const SET_IS_INSERT = 'SET_IS_INSERT'

export const SET_MODEL_INFO  = 'SET_MODEL_INFO'

export const SET_FOLLOW_ITEM = 'SET_FOLLOW_ITEM'

export const SET_CURRENT_TAB_INDEX = 'SET_CURRENT_TAB_INDEX'

export const SET_CURRENT_TAB_CONTENT = 'SET_CURRENT_TAB_CONTENT'

export const GET_REFERRER = 'GET_REFERRER'

export const GET_PERSON_INFO = 'GET_PERSON_INFO' 

export const GET_DISPLAYNAME_INFO = 'GET_DISPLAYNAME_INFO'


