export const GET_MARKET_LIST = 'GET_MARKET_LIST'

export const GET_MARKET_DETAIL = 'GET_MARKET_DETAIL' 

export const QUERY_INVITEL_LIST = 'QUERY_INVITEL_LIST'

export const CUST_REL_MATKET = 'CUST_REL_MATKET'

export const GET_LISTRELATION_CODE = 'GET_LISTRELATION_CODE'